# Generated by Django 2.1.5 on 2020-02-26 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoraildjango',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Base'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutoraildjango',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
