# Generated by Django 2.1.5 on 2020-02-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200226_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoraildjango',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
